spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/rest_api

    username: tester
    password: 1234
  jpa:
    properties:
      hibernate:
        format_sql: true
#        show_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE